on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: true
      matrix:
        otp: ["26", "27"]
        elixir: ["1.16", "1.17"]
        exclude:
          - otp: "27"
          - elixir: "1.16"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get --only prod
      - run: mix test
